version: "3.7"

services:
  dev-cron-backups-app:
    build: .
    image: dev-cron-backups-app
    container_name: dev-cron-backups-app
    restart: unless-stopped
    environment:
      DROPBOX_ACCESS_TOKEN: "${DROPBOX_ACCESS_TOKEN}"
    networks:
      home-services:

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16