version: "3.7"

services:
  prd-adguard-home-app:
    build: .
    image: prd-adguard-home-app
    container_name: prd-adguard-home-app
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PUID: "1000"
      PGID: "1000"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
    networks:
      - home-services
    volumes:
      - ./confdir:/opt/adguardhome/conf
      - ./workdir:/opt/adguardhome/work
    healthcheck:
      test: wget http://localhost:3000 --no-check-certificate -q -O - > /dev/null 2>&1
      interval: 1m30s
      timeout: 10s
      retries: 3

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16