version: '3.7'
services:

  prd-plex-app:
    image: plexinc/pms-docker
    container_name: prd-plex-app
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      PLEX_CLAIM: "${PLEX_CLAIMTOKEN}"
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      home-services:
    volumes:
      - ./database:/config
      - ./transcode/:/transcode
      - ./media:/data

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16