version: "3.7"

services:
  prd-cron-backups-app:
    build: .
    image: prd-cron-backups-app
    container_name: prd-cron-backups-app
    restart: unless-stopped
    environment:
      DROPBOX_ACCESS_TOKEN: "${DROPBOX_ACCESS_TOKEN}"
    networks:
      home-services:
    volumes:
      - ./backups:/backups
      - ../prd-esphome:/data/prd-esphome
      - ../prd-home-assistant:/data/prd-home-assistant

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16