version: '3.7'
services:

  prd-home-assistant-app:
    image: prd-home-assistant-app:latest
    container_name: prd-home-assistant-app
    depends_on:
      prd-home-assistant-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./config:/config
    environment:
      TZ: "${TZ}"
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 1m
      timeout: 10s
      retries: 3

  prd-home-assistant-db:
    image: mariadb:latest
    container_name: prd-home-assistant-db
    restart: always
    volumes:
      - prd-home-assistant-db-data:/var/lib/mysql
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${HOME_ASSISTANT_MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${HOME_ASSISTANT_MYSQL_DATABASE}"
      MYSQL_USER: "${HOME_ASSISTANT_MYSQL_USER}"
      MYSQL_PASSWORD: "${HOME_ASSISTANT_MYSQL_PASSWORD}"
    ports:
      - 3306:3306
    networks:
      home-services:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# VOLUMES
volumes:

  prd-home-assistant-db-data:
    name: prd-home-assistant-db-data

# NETWORKS
networks:

  home-services:
    driver: bridge
    name: home-services
    ipam:
      config:
        - subnet: 172.20.0.0/16