version: '3.8'

services:
  prd-dsmr-reader-app:
    build: .
    image: xirixiz/dsmr-reader-docker:latest
    container_name: prd-dsmr-reader-app
    depends_on:
      - prd-dsmr-reader-db
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dsmr_backups:/dsmr/backups
    environment:
      DJANGO_TIME_ZONE: "${TZ}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      DSMRREADER_ADMIN_USER: "${DSMRREADER_ADMIN_USER}"           # Webinterface user
      DSMRREADER_ADMIN_PASSWORD: "${DSMRREADER_ADMIN_PASSWORD}"   # Webinterface user password
      DSMRREADER_LOGLEVEL: "${DSMRREADER_LOGLEVEL}"               # Valid values are WARNING, INFO, DEBUG
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
    ports:
      - 7777:80
      - 7779:443
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0

  prd-dsmr-reader-db:
    image: postgres:12
    container_name: prd-dsmr-reader-db
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database:/var/lib/postgresql/data
    environment:
      TZ: "${TZ}"
      PG_TZ: "${TZ}"
      POSTGRES_USER: "${DSMRREADER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${DSMRREADER_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${DSMRREADER_POSTGRES_DB}"
      DJANGO_DATABASE_HOST: "${DJANGO_DATABASE_HOST}"