version: '3'

services:
  prd-esphome-app:
    image: esphome/esphome
    container_name: prd-esphome-app
    restart: always
    environment:
      ESPHOME_DASHBOARD_USE_PING: "${ESPHOME_DASHBOARD_USE_PING}"
      USERNAME: "${USERNAME}"  
      PASSWORD: "${PASSWORD}" 
    network_mode: host  
    volumes:
      - ./config:/config:rw
      - /etc/localtime:/etc/localtime:ro

